name: instagram_flutter
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: 
  cloud_firestore: 4.3.2
  cloud_firestore_platform_interface: 5.10.2
  cloud_firestore_web: 3.2.2
  firebase_auth: 
  firebase_storage: 
  flutter_svg: 
  image_picker: 
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:
  uuid: 
  intl: 
  logger: 
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  build_runner: 
  freezed:
  riverpod_generator: 
  json_serializable:
  custom_lint:
  riverpod_lint:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/