// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMfeA7xKP2uSiACMxKKhDG_EnpubFPZU',
    appId: '1:1020455862025:web:2c3b343ac82eaa378a5dd8',
    messagingSenderId: '1020455862025',
    projectId: 'insta-clone-8b4d8',
    authDomain: 'insta-clone-8b4d8.firebaseapp.com',
    storageBucket: 'insta-clone-8b4d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9l-ZMXpQLImKSbuqIZ2911RgorSzdibQ',
    appId: '1:1020455862025:android:24d1edc228943bca8a5dd8',
    messagingSenderId: '1020455862025',
    projectId: 'insta-clone-8b4d8',
    storageBucket: 'insta-clone-8b4d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtfwfjX0NGfS8bAXqNc1QsJ4CXeo6GtM',
    appId: '1:1020455862025:ios:f3e3f6dd3bf83b928a5dd8',
    messagingSenderId: '1020455862025',
    projectId: 'insta-clone-8b4d8',
    storageBucket: 'insta-clone-8b4d8.appspot.com',
    iosClientId: '1020455862025-tbet28tcei9h3j2n3h141dl1biprt14k.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
